# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/novokrest/GitHub/GeoScan/Photo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/novokrest/GitHub/GeoScan/Photo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/novokrest/GitHub/GeoScan/Photo/CMakeFiles /home/novokrest/GitHub/GeoScan/Photo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/novokrest/GitHub/GeoScan/Photo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named photobooth

# Build rule for target.
photobooth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photobooth
.PHONY : photobooth

# fast build rule for target.
photobooth/fast:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/build
.PHONY : photobooth/fast

#=============================================================================
# Target rules for targets named photobooth_automoc

# Build rule for target.
photobooth_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photobooth_automoc
.PHONY : photobooth_automoc

# fast build rule for target.
photobooth_automoc/fast:
	$(MAKE) -f CMakeFiles/photobooth_automoc.dir/build.make CMakeFiles/photobooth_automoc.dir/build
.PHONY : photobooth_automoc/fast

photobooth_automoc.o: photobooth_automoc.cpp.o
.PHONY : photobooth_automoc.o

# target to build an object file
photobooth_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/photobooth_automoc.cpp.o
.PHONY : photobooth_automoc.cpp.o

photobooth_automoc.i: photobooth_automoc.cpp.i
.PHONY : photobooth_automoc.i

# target to preprocess a source file
photobooth_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/photobooth_automoc.cpp.i
.PHONY : photobooth_automoc.cpp.i

photobooth_automoc.s: photobooth_automoc.cpp.s
.PHONY : photobooth_automoc.s

# target to generate assembly for a file
photobooth_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/photobooth_automoc.cpp.s
.PHONY : photobooth_automoc.cpp.s

qrc_photobooth.o: qrc_photobooth.cpp.o
.PHONY : qrc_photobooth.o

# target to build an object file
qrc_photobooth.cpp.o:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/qrc_photobooth.cpp.o
.PHONY : qrc_photobooth.cpp.o

qrc_photobooth.i: qrc_photobooth.cpp.i
.PHONY : qrc_photobooth.i

# target to preprocess a source file
qrc_photobooth.cpp.i:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/qrc_photobooth.cpp.i
.PHONY : qrc_photobooth.cpp.i

qrc_photobooth.s: qrc_photobooth.cpp.s
.PHONY : qrc_photobooth.s

# target to generate assembly for a file
qrc_photobooth.cpp.s:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/qrc_photobooth.cpp.s
.PHONY : qrc_photobooth.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/chdkptpmanager.o: src/chdkptpmanager.cpp.o
.PHONY : src/chdkptpmanager.o

# target to build an object file
src/chdkptpmanager.cpp.o:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/chdkptpmanager.cpp.o
.PHONY : src/chdkptpmanager.cpp.o

src/chdkptpmanager.i: src/chdkptpmanager.cpp.i
.PHONY : src/chdkptpmanager.i

# target to preprocess a source file
src/chdkptpmanager.cpp.i:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/chdkptpmanager.cpp.i
.PHONY : src/chdkptpmanager.cpp.i

src/chdkptpmanager.s: src/chdkptpmanager.cpp.s
.PHONY : src/chdkptpmanager.s

# target to generate assembly for a file
src/chdkptpmanager.cpp.s:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/chdkptpmanager.cpp.s
.PHONY : src/chdkptpmanager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/parameterslider.o: src/parameterslider.cpp.o
.PHONY : src/parameterslider.o

# target to build an object file
src/parameterslider.cpp.o:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/parameterslider.cpp.o
.PHONY : src/parameterslider.cpp.o

src/parameterslider.i: src/parameterslider.cpp.i
.PHONY : src/parameterslider.i

# target to preprocess a source file
src/parameterslider.cpp.i:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/parameterslider.cpp.i
.PHONY : src/parameterslider.cpp.i

src/parameterslider.s: src/parameterslider.cpp.s
.PHONY : src/parameterslider.s

# target to generate assembly for a file
src/parameterslider.cpp.s:
	$(MAKE) -f CMakeFiles/photobooth.dir/build.make CMakeFiles/photobooth.dir/src/parameterslider.cpp.s
.PHONY : src/parameterslider.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... photobooth"
	@echo "... photobooth_automoc"
	@echo "... rebuild_cache"
	@echo "... photobooth_automoc.o"
	@echo "... photobooth_automoc.i"
	@echo "... photobooth_automoc.s"
	@echo "... qrc_photobooth.o"
	@echo "... qrc_photobooth.i"
	@echo "... qrc_photobooth.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/chdkptpmanager.o"
	@echo "... src/chdkptpmanager.i"
	@echo "... src/chdkptpmanager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/parameterslider.o"
	@echo "... src/parameterslider.i"
	@echo "... src/parameterslider.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

